#!/bin/bash

cd $(dirname $0)/..

function die() {
  echo "$1"
  exit 1
}

MONGO_PORT=27017
which nc &>/dev/null && nc -vz localhost $MONGO_PORT 2>/dev/null || die "Can't find MongoDB on port $MONGO_PORT (using: nc -vz localhost $MONGO_PORT) - you may want to run 'docker run -p ${MONGO_PORT}:${MONGO_PORT} -d mongo'"

which nc &>/dev/null && nc -vz localhost $SERVICE_PORT 2>/dev/null && die "It appears the service is already running?"

which sm2 &>/dev/null || die "Can't find Service Manager"

sm2 --start ITSA_SUBSC_MIN "${@}"
sleep 5

sm2 --stop INCOME_TAX_SUBSCRIPTION_SELF_EMPLOYED_FRONTEND
sleep 5

sbt "run -Dapplication.router=testOnlyDoNotUseInAppConf.Routes"
